### ISSUE TITLE
Scenario information quest

### ISSUE THREAD

**Issue by visionchan** [swagshaw/WildDESED#1]
Dear Dr. Austin,

Thank you for contributing to the research field of Acoustic Event  Detection, and sharing this database with us.

I have a question about some scenario information in this database. Could you please release some scenario information on mixed audio files? It perhaps means that WAV files have the scenario label.

Thanks again for your help. 

Best wishes :)

**Comment by swagshaw** [comment]
Thank you for your kind words and your interest in our database. 😄  I’m glad to hear that it is useful for your research.

Regarding your question, the metadata for the mixed audio files is still being cleaned, but I will be sure to release it soon. In the meantime, if you'd like, you can send your email address here, and I would be happy to send you a raw version of the metadata for you to have a look at.

Please don't hesitate to reach out if you have any further questions or need additional help.

Best wishes,

**Comment by swagshaw** [comment]
> Thank you for your kind words and your interest in our database. 😄 I’m glad to hear that it is useful for your research.
> 
> Regarding your question, the metadata for the mixed audio files is still being cleaned, but I will be sure to release it soon. In the meantime, if you'd like, you can send your email address here, and I would be happy to send you a raw version of the metadata for you to have a look at.
> 
> Please don't hesitate to reach out if you have any further questions or need additional help.
> 
> Best wishes,

@visionchan

**Comment by visionchan** [comment]
> > Thank you for your kind words and your interest in our database. 😄 I’m glad to hear that it is useful for your research.
> > Regarding your question, the metadata for the mixed audio files is still being cleaned, but I will be sure to release it soon. In the meantime, if you'd like, you can send your email address here, and I would be happy to send you a raw version of the metadata for you to have a look at.
> > Please don't hesitate to reach out if you have any further questions or need additional help.
> > Best wishes,
> 
> @visionchan

I wanted to express my sincere gratitude for your prompt assistance. My Email is vision_chan@hotmail.com. Please send me a raw version of the metadata.

**Comment by swagshaw** [comment]
Sent you, please check

**Comment by peterwilson3912** [comment]
Thank you so much for this great project!  I am wondering what you mean by "mixed audio files are still being cleaned". what kind of cleaning process is it? Thank you so much for your help!

**Comment by swagshaw** [comment]
> Thank you so much for this great project!  I am wondering what you mean by "mixed audio files are still being cleaned". what kind of cleaning process is it? Thank you so much for your help!

Thank you for being interested in my work. For "mixed audio files are still being cleaned", the meta information is in several different files, later I will merge them to a more clear format.

**Comment by peterwilson3912** [comment]
> > Thank you so much for this great project!  I am wondering what you mean by "mixed audio files are still being cleaned". what kind of cleaning process is it? Thank you so much for your help!
> 
> Thank you for being interested in my work. For "mixed audio files are still being cleaned", the meta information is in several different files, later I will merge them to a more clear format.

sorry, i still don't understand what you mean. could you elaborate more?
